### ISSUE TITLE
`Scripts-HTR/1.MotifPresentation/shade_logo2.pl` failed to run.

### ISSUE THREAD

**Issue by Shunsuke-1994** [zhjilin/rmap#1]
Hi, thank you for providing the scripts for your interesting pipeline!
I am interested in running your scripts! 

But I encountered a problem regarding running `Scripts-HTR/1.MotifPresentation/shade_logo2.pl`. 
Looking at `Scripts-HTR/1.MotifPresentation/work.sh`, this file seems just running `shade_logo2.pl` as follows:
```
perl shade_logo2.pl RBM4_TTCGGA40NCGC_AAG_KGUUGCGCGGG_m2_c3_short.pfm RBM4_TTCGGA40NCGC_AAG_KGUUGCGCGGG_m2_c3.svg_slm.svg.BP.percent
``` 
However, I couldn't find any ".pfm" file although RBM4_TTCGGA40NCGC_AAG_KGUUGCGCGGG_m2_c3.svg_slm.svg.BP.percent was found in `Scripts-HTR/1.MotifPresentation/basepairinginfo.zip`. 
Besides, it seems that the information about which two positions form base-pairing is obtained before this code updated in this repository. How can I get "~~BP.percent" file from fastq files?

It would be very helpful if you would give me your guide about it.

Best, 
Shunsuke

**Comment by zhjilin** [comment]
Hi Shunsuke,
1. The motifs have been included in the supplemental tables. You could
parse them out into pfm for each motif.
2. The base pairing information cannot be obtained directly from fastq. The
kmer analysis and motif discovery steps need to be performed. The elife
paper by Nitta et al. 2015 described motif discovery.
Hope this helps.

Best,
Jilin

**Comment by Shunsuke-1994** [comment]
Hi Jilin, 

Thank you for your kind reply.

I ran the autoseed program provided as a supplementary file in (Nitta et al., elife, 2015) and I understand heatmaps like Fig.2AB in (Jolma/Zhang/Mondragón, Genome Res., 2020) can be generated through outputs of the autoseed program.
However, I am still wondering how the information about base pairing comes. I also checked the supplementary text in (Jolma/Zhang/Mondragón, Genome Res., 2020) and it looks that the base pairings were visually determined from the heatmap.

I would greatly appreciate if you could tell whether this impression is correct.

Sincerely, 
Shunsuke

**Comment by zhjilin** [comment]
Hi Shunsuke,
The motifs need to be determined based on heatmap first, then the base
pairing information can be extracted.

Best,
Jilin

**Comment by Shunsuke-1994** [comment]
Hi, Jilin, 

Thank you for your reply again.
It really helps. 

Best, 
Shunsuke
